### ISSUE TITLE
I'm that superniche...

### ISSUE THREAD

**Issue by AndreiD** [shazow/ethspam#11]
## How do I do that...put my screensaver on it ? 

I use mac and linux

**Comment by shazow** [comment]
Open a terminal, make it full screen, run ethspam? 😅 If there are any screensavers that render stdin, that would work too.

**Comment by AndreiD** [comment]
oky ... I thought. you have something smarter....without makign teh goddamn terminal fullscreen everytime

**Comment by shazow** [comment]
Sounds like you have your next project figured out! Ping here when you build a native ethspam screensaver and I'll link to it. :)
